security:
  jwt:
    token:
      secret-key: 53cce37
      expire-length: 3600000
spring:
  application:
    name:  financial_organizer

  profiles:
    active: test

  jpa:
    open-in-view: false

